In [3]:
import  numpy as np

In [4]:
my_list = [10,20,30,40]

In [5]:
type(my_list)

list

In [6]:
np.array(my_list)

array([10, 20, 30, 40])

In [7]:
my_numpy_array = np.array(my_list)

In [8]:
type(my_numpy_array)

numpy.ndarray

In [9]:
my_numpy_array.

np.int64(40)

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.random.random(5)

array([0.17233741, 0.16017498, 0.19072093, 0.58499779, 0.59475324])